- name: Agent prerequisites
  hosts: static,private_hosts
  gather_facts: true
  become: true
  tasks:
    - name: Install apt packages
      ansible.builtin.apt:
        name:
          - python3-pip
        update_cache: true
        state: present
    - name: Set global comm password
      ansible.builtin.shell: |
        echo 'GLOBAL_ACTION_PASSWORD="{{ global_comm_password }}"' >> /etc/environment
        echo 'GLOBAL_ACTION_SERVER="{{ global_comm_ip }}"' >> /etc/environment
        echo 'GLOBAL_COMM_PASSWORD="{{ global_comm_password }}"' >> /etc/environment
        echo 'GLOBAL_COMM_IP="{{ global_comm_ip }}"' >> /etc/environment
        echo 'LOCAL_ACTION_PASSWORD="{{ local_action_password }}"' >> /etc/environment
        echo 'LOCAL_ACTION_SERVER="{{ local_action_server_ip }}"' >> /etc/environment

    - name: Clone ai-stack
      ansible.builtin.git:
        repo: https://github.com/action-ai-institute/ai-stack.git
        dest: /opt/ai-stack
        version: main

    - name: Install ai-stack
      ansible.builtin.pip:
        name: /opt/ai-stack